      testimonials: [
        { slot: "t-ayesha", initials: "AS", name: "Ayesha Siddiqui", area: "Gulshan-e-Iqbal, Karachi",
          concern: "Acne & acne scars", stars: "★★★★★", rating: "5.0",
          doctor: "Dr. Zafar Ahmed", when: "3 weeks ago",
          quote: "I had been swapping creams on my own for almost two years. He checked my skin type first, put me on a proper course and told me exactly what each medicine was doing. The marks started fading by the second month." },
        { slot: "t-bilal", initials: "MB", name: "Muhammad Bilal", area: "North Nazimabad, Karachi",
          concern: "Hair fall & alopecia", stars: "★★★★★", rating: "4.8",
          doctor: "Dr. Shamail Zia", when: "1 month ago",
          quote: "He did not push me straight into a transplant. He ran the blood tests first, found the deficiency, and started PRP only after that. Honest about how long it would take, which I appreciated." },
        { slot: "t-hina", initials: "HR", name: "Hina Raza", area: "DHA Phase 6, Karachi",
          concern: "Melasma & dark spots", stars: "★★★★☆", rating: "4.5",
          doctor: "Dr. Anita Kazi", when: "2 months ago",
          quote: "The pigmentation on my cheeks had not moved in years. Four sessions in, it is noticeably lighter. She was clear that melasma comes back if I skip sunscreen, so I knew what I was signing up for." },
        { slot: "t-sana", initials: "SK", name: "Sana Khalid", area: "Bahadarabad, Karachi",
          concern: "Eczema & dermatitis", stars: "★★★★★", rating: "5.0",
          doctor: "Dr. Saima", when: "5 weeks ago",
          quote: "Booked the video consultation because my son's rash flared at night and I could not get out. She saw it on camera, prescribed there and then, and followed up after four days. Rs. 300 well spent." },
        { slot: "t-faisal", initials: "FM", name: "Faisal Mehmood", area: "Clifton, Karachi",
          concern: "Warts & mole removal", stars: "★★★★★", rating: "4.9",
          doctor: "Dr. Anita Kazi", when: "6 weeks ago",
          quote: "Two moles removed in one sitting. She explained which one needed to be sent for testing and why, instead of just taking them off. Healed clean, barely any mark left now." },
        { slot: "t-rabia", initials: "RN", name: "Rabia Noor", area: "PECHS, Karachi",
          concern: "Laser hair removal", stars: "★★★★☆", rating: "4.6",
          doctor: "Dr. Shamail Zia", when: "2 months ago",
          quote: "The clinic told me upfront it would take six sessions rather than promising results in two, and the per-session fee was exactly what was quoted on Marham. No surprise charges at the counter." }
      ],

